ALTER TABLE entries ADD COLUMN completed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN guard_passed INTEGER NOT NULL DEFAULT 1;
ALTER TABLE entries ADD COLUMN guard_flags TEXT NOT NULL DEFAULT '[]';
